networks:
  network:
    name: ${PROJECT_NAME}-network

services:
  asgi:
    extends:
      file: docker-compose.yml
      service: asgi
    image: ${REGISTRY}/{IMAGE_NAME}:${IMAGE_TAG:-latest}
    platform: linux/amd64
