networks:
  network:
    name: ${PROJECT_NAME}-network

services:
  asgi:
    container_name: ${PROJECT_NAME}-asgi
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: ${ASGI_TARGET}
    env_file:
      - .env
    volumes:
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
    ports:
      - ${PORT}:${PORT}
    networks:
      - network
    restart: ${RESTART_POLICY:-unless-stopped}
    cpus: ${ASGI_CPUS:-0.000}
    mem_limit: ${ASGI_MEM_LIMIT:-1G}
    mem_reservation: ${ASGI_MEM_RESERVATION:-500M}
