networks:
  network:
    name: ${PROJECT_NAME}-network

services:
  asgi:
    extends:
      file: docker-compose.yml
      service: asgi
    env_file:
      - .env
    volumes:
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
      - ../src/:/apps/
