networks:
  network:
    name: ${PROJECT_NAME}-network

volumes:
  redis-data:
    name: ${PROJECT_NAME}-redis-data

services:
  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:${REDIS_VERSION}
    command:
      - "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    networks:
      - network
    restart: ${RESTART_POLICY:-unless-stopped}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    cpus: ${REDIS_CPUS:-0.000}
    mem_limit: ${REDIS_MEM_LIMIT:-1G}
    mem_reservation: ${REDIS_MEM_RESERVATION:-500M}

  asgi:
    extends:
      file: docker-compose.yml
      service: asgi
    env_file:
      - .env
    volumes:
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
      - ../src/:/apps/
