networks:
  network:
    name: {{ env.PROJECT_NAME }}-network

services:
  asgi:
    extends:
      file: docker-compose.yml
      service: asgi
    image: {{ env.REGISTRY }}/{{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG:-latest }}
    platform: linux/amd64
