#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
- name: {{ env.USERNAME }}
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  shell: /bin/bash
  ssh_authorized_keys:
  - {{ env.SSH_PUBLIC_KEY }}
write_files:
  - path: "/usr/local/etc/docker-start.sh"
    permissions: "755"
    content: |
      #!/bin/bash

      # Docker
      echo "Installing Docker"
      sudo apt update -y && sudo apt install docker.io -y
      echo "Grant user access to Docker"
      sudo usermod -aG docker ${USER}
      newgrp docker

    defer: true
  - path: "/usr/local/etc/docker-main.sh"
    permissions: "755"
    content: |
      #!/bin/bash

      # Docker run container
      docker pull {{ env.REGISTRY }}/{{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }}
      docker run {{ env.REGISTRY }}/{{ env.IMAGE_NAME }}

    defer: true
runcmd:
  - [su, {{ env.USERNAME }}, -c, "/usr/local/etc/docker-start.sh"]
  - [su, {{ env.USERNAME }}, -c, "/usr/local/etc/docker-main.sh"]
