name: Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to root of repo
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          REGISTRY: ${{ secrets.YC_CR_REGISTRY }}
          IMAGE_NAME: ${{ secrets.YC_CR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker compose -f docker/docker-compose.main.yml -p matveyivanov build
          docker compose -f docker/docker-compose.main.yml -p matveyivanov push

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-service-account-id: ${{ secrets.YC_REVISION_SERVICE_ACCOUNT_ID }}
          revision-cores: ${{ secrets.YC_REVISION_CORES }}
          revision-memory: ${{ secrets.YC_REVISION_MEMORY }}
          revision-core-fraction: ${{ secrets.YC_REVISION_CORE_FRACTION }}
          revision-concurrency: ${{ secrets.YC_REVISION_CONCURRENCY }}
          revision-image-url: ${{ secrets.YC_IMAGE_URL }}:latest
          revision-execution-timeout: ${{ secrets.YC_REVISION_EXECUTION_TIMEOUT }}
          revision-env: ${{ secrets.YC_REVISION_ENV }}
