name: Locations Function

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths:
      - ".github/**"
      - "f-locations/**"

jobs:
  core-compare:
    uses: ./.github/workflows/core-compare.yml
  linters:
    uses: ./.github/workflows/linting.yml
  build:
    name: Deploy new locations function version 
    runs-on: ubuntu-latest
    needs:
      - core-compare
      - linters
    steps:
      - name: Checkout to root of repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            f-locations

      - name: Prepare directory structure for deploy
        run: |
          mv f-locations f-locations-tmp
          cp -R f-locations-tmp/* .
          rm -rf f-locations-tmp
          rm -rf .git

      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v3
        with:
          runtime: 'python312'
          entrypoint: 'main.handler'
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          memory: ${{ secrets.YC_F_LOCATIONS_MEMORY }}
          execution-timeout: ${{ secrets.YC_F_LOCATIONS_EXECUTION_TIMEOUT }}
          folder-id: ${{ secrets.YC_F_LOCATIONS_FOLDER_ID }}
          function-name: ${{ secrets.YC_F_LOCATIONS_FUNCTION_NAME}}
          service-account: ${{ secrets.YC_F_LOCATIONS_SERVICE_ACCOUNT_ID }}
          network-id: ${{ secrets.YC_F_LOCATIONS_NETWORK_ID }}
          environment: |
            SQS_SECRET_KEY=${{ secrets.SQS_LOCATIONS_SECRET_KEY }}
            SQS_ACCESS_KEY=${{ secrets.SQS_LOCATIONS_ACCESS_KEY }}
            SQS_REGION_NAME=${{ secrets.SQS_LOCATIONS_REGION_NAME }}
            SQS_ENDPOINT_URL=${{ secrets.SQS_LOCATIONS_ENDPOINT_URL }}
            SQS_QUEUE_URL=${{ secrets.SQS_LOCATIONS_QUEUE_URL }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            REDIS_SOCKET_TIMEOUT=${{ secrets.YC_F_LOCATIONS_REDIS_SOCKET_TIMEOUT }}
            REDIS_SOCKET_CONNECTION_TIMEOUT=${{ secrets.YC_F_LOCATIONS_REDIS_SOCKET_CONNECTION_TIMEOUT }}
            IPINFO_ACCESS_TOKEN=${{ secrets.IPINFO_ACCESS_TOKEN }}
            IPINFO_TIMEOUT=${{ secrets.YC_F_LOCATIONS_IPINFO_TIMEOUT }}
            IPINFO_DEFAULT_CITY=${{ secrets.YC_F_LOCATIONS_IPINFO_DEFAULT_CITY }}
            LOCATIONS_BUFFER_NAME=${{ secrets.LOCATIONS_BUFFER_NAME }}
            LOCATIONS_BUFFER_MAX_SIZE=${{ secrets.LOCATIONS_BUFFER_MAX_SIZE }}
            LOCATIONS_HASHSET_NAME=${{ secrets.LOCATIONS_HASHSET_NAME }}
          include: |
            ./
