name: Linting

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  linters:
    name: Run linters for the whole codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: pip install poetry==2.1.1
      - run: cd src && poetry install
      - run: |
          make lint
          make formatcheck
          make sortcheck
          make analyze
          make test || true
