name: Tests, linters, analyzers and formatters

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install poetry==2.1.1
      - run: cd src && poetry install
      - run: |
          make lint
          make formatcheck
          make sortcheck
          make analyze
          make test || true
